# Generated by Django 2.2.2 on 2019-06-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=350)),
                ('image', models.ImageField(upload_to='images/')),
                ('github_link', models.CharField(max_length=60)),
                ('link', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
